import { z } from "zod";
import type { BlockField } from "@/types/block";

export const scratchConfigSchema = z.object({
  eyebrow: z.string().optional(),
  title: z.string().optional(),
  subtitle: z.string().optional(),
  instruction: z.string().optional(),
  winText: z.string().optional(),
  loseText: z.string().optional(),
  scratchBackground: z.string().optional(),
  externalBackground: z.string().optional(),
  borderColor: z.string().optional(),
  borderRadius: z.number().optional(),
  maxWidth: z.number().optional(),
  gridSize: z.enum(["2x2", "3x3", "4x4"]).optional(),
  gridGap: z.number().optional(),
  maskColor: z.string().optional(),
  maskTexture: z.string().optional(),
  centerIcon: z.string().optional(),
  maskOpacity: z.number().optional(),
  previewMode: z.boolean().optional(),
});

export const scratchDefaultConfig = {
  eyebrow: "TENTE A SORTE",
  title: "Raspadinha Premiada",
  subtitle: "Raspe e descubra se você ganhou",
  instruction: "Raspe as células abaixo. Encontre 3 iguais para ganhar!",
  winText: "Você ganhou!",
  loseText: "Não foi dessa vez.",
  scratchBackground: "#ffffff",
  externalBackground: "#f3f4f6",
  borderColor: "#e5e7eb",
  borderRadius: 8,
  maxWidth: 600,
  gridSize: "3x3",
  gridGap: 8,
  maskColor: "#9ca3af",
  maskTexture: "",
  centerIcon: "",
  maskOpacity: 1,
  previewMode: true,
};

export const scratchFields: BlockField[] = [
  { key: "eyebrow", label: "Eyebrow", type: "text" },
  { key: "title", label: "Título", type: "text" },
  { key: "subtitle", label: "Subtítulo", type: "textarea" },
  { key: "instruction", label: "Instrução", type: "textarea" },
  { key: "winText", label: "Texto de Vitória", type: "text" },
  { key: "loseText", label: "Texto de Derrota", type: "text" },
  { key: "scratchBackground", label: "Cor de Fundo (Interno)", type: "color" },
  { key: "externalBackground", label: "Cor de Fundo (Externo)", type: "color" },
  { key: "borderColor", label: "Cor da Borda", type: "color" },
  { key: "borderRadius", label: "Arredondamento (px)", type: "number" },
  { key: "maxWidth", label: "Largura Máxima (px)", type: "number" },
  {
    key: "gridSize",
    label: "Tamanho da Grade",
    type: "select",
    options: [
      { label: "2x2", value: "2x2" },
      { label: "3x3", value: "3x3" },
      { label: "4x4", value: "4x4" },
    ],
  },
  { key: "gridGap", label: "Espaçamento da Grade (px)", type: "number" },
  { key: "maskColor", label: "Cor da Máscara", type: "color" },
  { key: "maskTexture", label: "Textura da Máscara (URL)", type: "url" },
  { key: "centerIcon", label: "Ícone Central (URL)", type: "url" },
  { key: "maskOpacity", label: "Opacidade da Máscara (0-1)", type: "number" },
  { key: "previewMode", label: "Modo de Pré-visualização", type: "toggle" },
];
