"use client";

import { useEffect, useMemo, useState } from "react";
import type { BoosterFunnelConfig } from "@/lib/blocks/booster-funnel";

const symbols = ["⚡", "🎯", "🎁", "⭐", "⚡", "🏅", "🎪", "🎰", "⚡"];
const labels = ["110X", "BÔNUS", "SORTEIO", "EXTRA", "110X", "PRÊMIO", "PLUS", "TURBO", "110X"];
const lines = (value: string) => value.split("\n").map((line, index) => <span key={index}>{line}<br /></span>);

export function BoosterFunnelBlock({ config, preview = false }: { config: BoosterFunnelConfig; preview?: boolean }) {
  const [stage, setStage] = useState<"scratch" | "unlock" | "offer">(preview ? config.previewStage : "scratch");
  const [revealed, setRevealed] = useState<boolean[]>(Array(9).fill(false));
  const [seconds, setSeconds] = useState(config.countdownMinutes * 60);
  const cssVars = { "--bf-green": config.accentColor, "--bf-yellow": config.highlightColor, "--bf-red": config.dangerColor } as React.CSSProperties;

  useEffect(() => { if (preview) setStage(config.previewStage); }, [config.previewStage, preview]);
  useEffect(() => {
    if (stage !== "offer") return;
    const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000);
    return () => window.clearInterval(timer);
  }, [stage]);
  useEffect(() => {
    if (revealed.every(Boolean) && !preview) window.setTimeout(() => setStage("unlock"), 450);
  }, [revealed, preview]);

  const clock = useMemo(() => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`, [seconds]);
  const reveal = (index: number) => setRevealed((current) => current.map((value, i) => i === index ? true : value));

  return (
    <div className="bf-root" style={cssVars}>
      <style>{`
        .bf-root{background:#030504;color:#fff;min-height:100%;font-family:Arial,Helvetica,sans-serif}.bf-root *{box-sizing:border-box}
        .bf-condensed{font-family:Impact,'Arial Narrow',sans-serif;letter-spacing:.02em}.bf-yellow{color:var(--bf-yellow)}
        .bf-stage{min-height:100dvh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% 48%,color-mix(in srgb,var(--bf-green) 12%,transparent),transparent 30%),#020403}
        .bf-scratch-card{width:min(340px,92vw);padding:27px 31px 20px;border:2px solid var(--bf-green);border-radius:20px;background:linear-gradient(145deg,#071500,#0b1604);box-shadow:0 0 42px color-mix(in srgb,var(--bf-green) 22%,transparent);text-align:center;position:relative}
        .bf-scratch-card:before{content:'';position:absolute;left:0;right:0;top:-2px;height:3px;background:linear-gradient(90deg,var(--bf-yellow),var(--bf-green) 25% 90%,transparent);border-radius:20px}
        .bf-brand{font-size:10px;letter-spacing:3px;color:var(--bf-green);font-weight:900;margin-bottom:10px}.bf-scratch-title{font-size:26px;line-height:.92;margin:0}.bf-scratch-sub{font-size:11px;color:#555;margin:7px 0 16px}
        .bf-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.bf-cell{aspect-ratio:1;border:1px solid #252b21;border-radius:8px;background:#151814;display:grid;place-items:center;position:relative;overflow:hidden;color:#fff;cursor:pointer}.bf-cell.win{border-color:var(--bf-green);box-shadow:inset 0 0 24px color-mix(in srgb,var(--bf-green) 18%,transparent)}
        .bf-symbol{font-size:25px;filter:drop-shadow(0 0 8px color-mix(in srgb,var(--bf-yellow) 45%,transparent))}.bf-label{display:block;font-size:7px;font-weight:900;color:#555}.bf-cell.win .bf-label{color:var(--bf-yellow)}
        .bf-mask{position:absolute;inset:0;background:linear-gradient(145deg,#2b2b2b,#1e1e1e);transition:.35s;display:grid;place-items:center}.bf-mask:after{content:'········';color:#343434;letter-spacing:2px}.bf-cell.revealed .bf-mask{opacity:0;transform:scale(.8);pointer-events:none}.bf-hint{font-size:10px;color:#666;margin-top:10px}
        .bf-unlock{width:min(360px,92vw);padding:28px 22px 22px;border-radius:22px;border:2px solid transparent;background:linear-gradient(#071207,#071207) padding-box,linear-gradient(145deg,var(--bf-green),var(--bf-yellow)) border-box;text-align:center;box-shadow:0 0 45px rgba(29,190,46,.17)}.bf-bolt{font-size:72px;line-height:1;filter:drop-shadow(0 0 18px rgba(255,212,0,.5))}.bf-unlock h2{font-size:37px;line-height:1.02;color:var(--bf-yellow);margin:10px 0 12px}.bf-unlock p{font-size:14px;line-height:1.55;color:#c5c5c5}.bf-access{border:1px solid #766700;border-radius:10px;padding:14px;color:var(--bf-yellow);font-size:12px;font-weight:900;margin:20px 0 12px}.bf-btn{display:flex;align-items:center;justify-content:center;width:100%;min-height:62px;border:0;border-radius:11px;background:#117b15;color:#fff;font-size:21px;font-weight:900;text-transform:uppercase;cursor:pointer;box-shadow:0 0 0 8px rgba(30,200,45,.08)}
        .bf-offer{background:#050505;min-height:100vh}.bf-topbar{height:44px;padding:0 16px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #191919;font-size:11px;font-weight:900}.bf-clock{font-size:22px;color:var(--bf-red);letter-spacing:1px}.bf-hero{text-align:center;padding:12px 18px 16px}.bf-badge{display:inline-block;border:1px solid #075b16;border-radius:20px;padding:5px 14px;color:var(--bf-green);font-size:9px;font-weight:900;letter-spacing:1.3px}.bf-hero h1{font-size:clamp(42px,6vw,70px);line-height:.88;margin:14px auto 10px}.bf-alert{border:1px solid #641919;background:#170909;border-radius:8px;padding:9px;color:var(--bf-red);font-size:12px;font-weight:900}.bf-desc{max-width:430px;margin:12px auto;color:#929292;font-size:14px;line-height:1.5}.bf-media{width:min(205px,80vw);aspect-ratio:3/4;margin:12px auto;border:2px solid #526b34;border-radius:13px;background:linear-gradient(145deg,#172713,#080b08);overflow:hidden;position:relative}.bf-media img{width:100%;height:100%;object-fit:cover}.bf-sound{position:absolute;left:14%;right:14%;top:40%;padding:13px;border-radius:999px;background:#cf3c32;border:2px solid #fff;color:#fff;font-size:15px;font-weight:900}.bf-wide-cta{margin:12px auto 0;max-width:1330px;min-height:62px;background:#147a16;border-radius:11px;color:#fff;text-decoration:none;font-size:24px}.bf-ticker{border-top:1px solid #222;border-bottom:1px solid #222;padding:9px;white-space:nowrap;overflow:hidden;color:#8d8d8d;font-size:10px}
        .bf-section{padding:58px 18px;text-align:center;border-bottom:1px solid #181818}.bf-container{width:min(480px,100%);margin:auto}.bf-eyebrow{font-size:9px;letter-spacing:4px;color:#666;font-weight:900}.bf-heading{font-size:clamp(32px,5vw,47px);line-height:.95;margin:10px 0 20px}.bf-status{border:1px solid #0f4c18;border-radius:9px;padding:10px;color:var(--bf-green);font-size:11px;font-weight:900}.bf-prize{display:flex;align-items:center;text-align:left;gap:12px;border:1px solid #175a1a;border-left:4px solid var(--bf-green);border-radius:10px;padding:10px 14px;margin:7px 0;background:#071307}.bf-prize strong{display:block;font-size:17px}.bf-prize small{color:var(--bf-green);font-size:10px}.bf-progress{border:1px solid #292929;border-radius:14px;padding:17px;text-align:left;background:#111}.bf-track{height:10px;border-radius:10px;background:#181818;overflow:hidden}.bf-track i{display:block;height:100%;background:linear-gradient(90deg,var(--bf-green),var(--bf-yellow));border-radius:10px}.bf-progress-row{display:flex;justify-content:space-between;align-items:end;margin-top:10px}.bf-progress-row strong{font-size:25px;color:var(--bf-yellow)}
        .bf-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px;text-align:left}.bf-side{border:1px solid #5b1515;background:#1a0505;border-radius:13px;padding:15px}.bf-side.good{border-color:#155d17;background:#061906}.bf-side b{display:block;font-size:50px;color:#711515;margin:10px 0}.bf-side.good b{color:#137d18}.bf-side li{font-size:12px;margin:9px 0;list-style:none}.bf-explain{border:1px solid #195d16;border-top:3px solid #58b900;background:#071907;border-radius:13px;padding:18px;text-align:left;line-height:1.7;font-size:13px}.bf-explain h3{color:var(--bf-yellow);font-size:20px}.bf-offer-card{position:relative;border:2px solid var(--bf-green);border-radius:20px;padding:28px 18px;background:linear-gradient(150deg,#0b2106,#050b04);box-shadow:0 0 45px rgba(0,200,35,.12)}.bf-offer-card h3{font-size:31px;color:var(--bf-yellow)}.bf-benefit{border-bottom:1px solid #1b2c18;padding:12px 0;text-align:left;font-size:13px}.bf-price{font-size:74px;color:var(--bf-yellow);margin:22px 0 6px}.bf-urgency{background:#170800;border:1px solid #814000;border-radius:14px;padding:24px;margin-top:28px;color:#ff8a1d}.bf-custom{} 
        @media(max-width:640px){.bf-stage{padding:14px}.bf-scratch-card{padding:23px 22px 18px}.bf-topbar{font-size:8px}.bf-clock{font-size:17px}.bf-hero h1{font-size:43px}.bf-wide-cta{font-size:19px;margin-inline:0}.bf-section{padding:45px 14px}.bf-compare{grid-template-columns:1fr}.bf-heading{font-size:34px}}
        ${config.customCss}
      `}</style>

      {stage === "scratch" && <section className="bf-stage"><div className="bf-scratch-card">
        <div className="bf-brand">⚡ {config.brandText}</div><h2 className="bf-condensed bf-scratch-title">{lines(config.scratchTitle)}</h2><p className="bf-scratch-sub">{config.scratchSubtitle}</p>
        <div className="bf-grid">{symbols.map((symbol,index)=><button type="button" key={index} onClick={()=>reveal(index)} className={`bf-cell ${index===0||index===4||index===8?"win":""} ${revealed[index]?"revealed":""}`}><div><span className="bf-symbol">{symbol}</span><span className="bf-label">{labels[index]}</span></div><span className="bf-mask" /></button>)}</div><div className="bf-hint">☝️ {config.scratchInstruction}</div>
        {preview && <button className="bf-btn" style={{marginTop:12,minHeight:40,fontSize:13}} onClick={()=>setStage("unlock")}>Prévia: continuar</button>}
      </div></section>}

      {stage === "unlock" && <section className="bf-stage"><div className="bf-unlock"><div className="bf-bolt">⚡</div><h2 className="bf-condensed">{lines(config.unlockTitle)}</h2><p>{config.unlockDescription}</p><div className="bf-access">🏆 ACESSO EXCLUSIVO LIBERADO — ATIVE AGORA</div><button className="bf-btn" onClick={()=>setStage("offer")}>🔒 {config.unlockCta}</button></div></section>}

      {stage === "offer" && <main className="bf-offer bf-custom">
        <div className="bf-topbar"><span>🔴 ⚠️ {config.reserveText}</span><strong className="bf-clock">{clock}</strong></div>
        <section className="bf-hero"><div className="bf-badge">● BOOSTER DESBLOQUEADO PARA VOCÊ</div><h1 className="bf-condensed">{lines(config.offerTitle)}</h1><div className="bf-alert">🚨 {config.alertText}</div><p className="bf-desc">{config.heroDescription}</p><div className="bf-media">{config.mediaUrl && <img src={config.mediaUrl} alt="Apresentação da oferta" />}<div className="bf-sound">🔇 {config.mediaButton}</div></div><a href={config.ctaUrl} className="bf-btn bf-wide-cta">⚡ {config.primaryCta}</a></section>
        <div className="bf-ticker">● Felipe M. ativou o Booster — Jetta GLI ainda disponível　 ● Carla S. entrou com 110X antes da cota sair　 ● Rodrigo T. está na frente de todo mundo</div>
        <section className="bf-section"><div className="bf-container"><div className="bf-eyebrow">O QUE ESTÁ EM JOGO AGORA</div><h2 className="bf-condensed bf-heading">{lines(config.prizeHeadline)}</h2><div className="bf-status">● Jetta GLI disponível — nenhuma cota encontrada ainda</div>{[["🚗","JETTA GLI 0KM","ENCONTROU, LEVOU NA HORA"],["💰","PIX R$ 1.000 CADA","9 DISPONÍVEIS NO SISTEMA"],["🚚","CAMINHÃO VW 11.180 + F-250","R$ 800.000 EM PRÊMIOS"]].map((item)=><div className="bf-prize" key={item[1]}><span style={{fontSize:26}}>{item[0]}</span><div><strong className="bf-condensed">{item[1]}</strong><small>{item[2]}</small></div></div>)}</div></section>
        <section className="bf-section"><div className="bf-container"><div className="bf-eyebrow">O QUE ESTÁ ACONTECENDO AGORA</div><h2 className="bf-condensed bf-heading">O JETTA GLI<br/>PODE SAIR <span className="bf-yellow">AGORA.</span></h2><div className="bf-progress"><small>CAMPANHA VENDEDOR SINCERO — ANDAMENTO</small><div className="bf-track"><i style={{width:`${config.progress}%`}} /></div><div className="bf-progress-row"><strong>{config.progress}%</strong><span>Campanha acelerada<br/><b>do Vendedor Sincero</b></span></div></div></div></section>
        <section className="bf-section"><div className="bf-container"><div className="bf-eyebrow">DOIS CAMINHOS À SUA FRENTE</div><h2 className="bf-condensed bf-heading">{lines(config.comparisonTitle)}</h2><div className="bf-compare"><div className="bf-side"><strong>✕ SEM BOOSTER</strong><b>95%</b><ul><li>✕ Poucos números, muita torcida</li><li>✕ Jetta sai para outro</li><li>✕ PIX vai para outra mão</li><li>✕ Caminhão vai para outra garagem</li></ul></div><div className="bf-side good"><strong>☑ BOOSTER ATIVO</strong><b>5%</b><ul><li>☑ 110X mais chances no Jetta GLI</li><li>☑ Forte nos 9 PIX R$ 1.000</li><li>☑ Na frente no Caminhão VW</li><li>☑ Ataca. Não torce.</li></ul></div></div></div></section>
        <section className="bf-section"><div className="bf-container"><div className="bf-eyebrow">POR QUE 110X MUDA TUDO</div><h2 className="bf-condensed bf-heading">{lines(config.explanationTitle)}</h2><div className="bf-explain"><div style={{fontSize:30}}>🎯</div><h3 className="bf-condensed">PENSE ASSIM:</h3><p>O sistema tem 10 milhões de números. Quem entra com poucos números cobre uma <b>fração mínima</b> desse campo.</p><p>Quem ativa o Booster 110X cobre <b className="bf-yellow">110X mais terreno</b> — mais Jetta, mais PIX, mais Caminhão VW. <b>Não é sorte. É cobertura.</b></p></div></div></section>
        <section className="bf-section" id="oferta"><div className="bf-container"><div className="bf-eyebrow">EXCLUSIVO — SÓ NESSA PÁGINA</div><h2 className="bf-condensed bf-heading">{lines(config.offerHeading)}</h2><div className="bf-offer-card"><h3 className="bf-condensed">BOOSTER {config.multiplier}</h3>{["110X mais chances de encontrar o Jetta GLI 0KM agora","110X mais chances nos 9 PIX de R$ 1.000 disponíveis","Posicionamento fortíssimo no Caminhão VW","R$ 800.000 em prêmios — você dentro de tudo"].map(x=><div className="bf-benefit" key={x}>✅ <b>{x}</b></div>)}<div className="bf-condensed bf-price">{config.price}</div><a href={config.ctaUrl} className="bf-btn">⚡ {config.primaryCta} AGORA</a></div><div className="bf-urgency"><b>⏰ ESSA JANELA FECHA EM BREVE</b><p>Oferta aparece uma única vez. Feche e desaparece.</p></div></div></section>
      </main>}
    </div>
  );
}
